---
# tasks file for k8s-create-user-and-context

- name: Credential creation
  command: >
    kubectl config set-credentials treeptik.student
    --kubeconfig treeptik-student-config
    --embed-certs=true
    --client-certificate=files/treeptik.student.pem
    --client-key=files/treeptik.student-key.pem

- name: Context creation
  command: >
    kubectl config set-context
    --kubeconfig treeptik-student-config treeptik-context
    --cluster="{{ clusterName }}"
    --user=treeptik.student
    --namespace=treeptik-namespace

- name: Context selection
  command: kubectl config use-context --kubeconfig treeptik-student-config treeptik-context

- name: Cluster selection
  command: >
    kubectl config set-cluster
    --kubeconfig treeptik-student-config "{{ clusterName }}"
    --insecure-skip-tls-verify=true
    --server="{{ serverAddress }}"
