---
# tasks file for create-user
- name: Generate an user key
  openssl_privatekey:
    path: files/treeptik.student-key.pem
    size: 2048

- name: Generate the user csr
  openssl_csr:
    path: files/treeptik.student.csr
    privatekey_path: files/treeptik.student-key.pem
    common_name: treeptik.student

- name: Set csr value
  shell: cat files/treeptik.student.csr | base64 | tr -d '\n'
  register: request
