apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: user-request-treeptik-student
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2ZqQ0NBV1lDQVFBd0d6RVpNQmNHQTFVRUF4TVFkSEpsWlhCMGFXc3VjM1IxWkdWdWREQ0NBU0l3RFFZSgpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNcUtSbys3WFZNV3o0bmZ3bVhobHBodDJ1NUdXbitDCkFnbVVMV1hCS2Yyclo3dGh6YjB0VVJIVkdGQlZ1N2R1dTROY1dlWUhBRnoyeWlzVkhXbkdxV2ZrS1RZTEppeGsKUWMzN1h6dW9YMmF6bFZBOGhvUEROMTZYNlZsV1d3K0tyeGpYMTd2Qmp1V05YYmZvNkRldE5TL0RhZTJqTERQUgpWekN4ajVwYWdScVNzMlBQanhjNzVUdkZKZTN3TUxLSmxZZE9kd2gwWHBNY3FwbEg1S2E3c2E5YjNVVHh3SitnCnorWDgxVEVGMGQ3RVJ5RWNEQ3F4dThVb2tuMmQ3NGJjbXJlMk1TVFZENTZLOXFzbGZXZFVnMUNVNUwzN1lBb2wKc25KeEpqajQ2YWhieWUvU0s1R1czRmQ2dFFSblUveklCVlQ1VmlWTk5uNk9USzJrTmxkN3hGOENBd0VBQWFBZQpNQndHQ1NxR1NJYjNEUUVKRGpFUE1BMHdDd1lEVlIwUkJBUXdBb0lBTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCCkFRQmw2M0JIVVNNbkRsQlROQ3VrZjVNU3hONUxOdHRzcVJSSy9TVEQyc0p6SDZxTnNzaHl3NlFPR0c0V0xCYWQKclExelVXQlVyejZ4b25uVHBTV3psM1NyMUU4TERnZmVhS0JWanpQYVRlRDljSGlINXZLY3EwU3BkOUVSUDRRMQpBQ2lGTFAwZElRL0diWmc4a296NXJvc3U4akpKeWRIYTBIQW9TUXVWNWEyYnNNRi8vK0hRT2RrcGFTNGt0MjdhClpINEpuenRpM0xpemNCOTlIV2ZzV3EvV0V6TmRZV2hMRU5aTkU3NUx5RnJqRjh6eXorcERiemdldXN2T200WVIKdFRoY3czcHlPUXE5dm90dW8wajRGWSsrTnI1TTUxZC9wNFp5VHFKOEFDQVdVcTFISHh2aFBkc0tTdXZ3T2pLTwp0NWEwajBEYVNaTzhpd0hSL0lJNHNQdGgKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  usages:
  - digital signature
  - key encipherment
  - client auth

